# Generated by Django 3.1.2 on 2020-11-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201116_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='system_type',
            field=models.CharField(choices=[(0, 'linux'), (1, 'Windows')], default=0, max_length=32),
        ),
    ]
