# Generated by Django 3.1.2 on 2020-11-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20201116_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteuser',
            name='aliasname',
            field=models.CharField(default='', max_length=128),
        ),
    ]
