# Generated by Django 3.1.2 on 2020-11-19 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_sessionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrecord',
            name='bind_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.bindhost'),
        ),
        migrations.AlterField(
            model_name='sessionrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='堡垒机账号'),
        ),
    ]
