# Generated by Django 3.1.2 on 2020-11-19 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20201119_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrecord',
            name='bind_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.bindhost'),
        ),
        migrations.AlterField(
            model_name='sessionrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='堡垒机账号'),
        ),
    ]
