# Generated by Django 3.1.3 on 2020-12-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20201119_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256, unique=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'websocket not connect'), (1, 'websocket open'), (2, 'websocket close')], default=0)),
                ('audit_log', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CmdRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ops_time', models.DateTimeField()),
                ('ops_user', models.EmailField(max_length=255, verbose_name='ops user')),
                ('host', models.GenericIPAddressField()),
                ('host_user', models.CharField(max_length=128)),
                ('cmd', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
