# Generated by Django 3.1.3 on 2020-12-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_audit_log_cmdrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audit_log',
            new_name='AuditLog',
        ),
    ]
