# Generated by Django 3.1.3 on 2021-01-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20201229_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'websocket not connect'), (1, 'websocket open'), (2, 'websocket close'), (3, 'analytics log done')], default=0),
        ),
    ]
